config/routes.rb
Rails.application.routes.draw do
  resources :concerts
  devise_for :users
  resources :songs
  resources :albums
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: "home#top"
  get "/about", to: "home#about"
  get "/music", to: "home#music"
  get "/music/albums", to: "albums#albums_index"
  get "/music/albums/:id", to: "albums#show"
  get "/music/singles", to: "albums#singles_index"
  
  get "/music/songs", to: "songs#index"
  
  get "/admin", to: "admin#admin_login"
  
  get "/concerts/:title/detail", to: "concerts#show"
  get "/concerts/:title/destroy", to: "concerts#destroy"
  
  get "/links", to: "home#links"
end

app/models/song.rb
class Song < ApplicationRecord
    has_many :album_songs
    has_many :albums, through: :album_songs
    has_many :setlists
    has_many :concerts, through: :setlists
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  PER = 15
  before_action :set_song, only: [:show, :edit, :update, :destroy]
  before_action :user_signed_in? , only: [:new, :create, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
  @songs = Song.all.page(params[:page]).per(PER)
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:title, :release, :lyricist, :composer) #{ album_ids: [] })
    end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.erb
<%= form_with(model: song, local: true) do |form| %>
  <% if song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :release %>
    <%= form.date_select( :release , start_year: 1991 , end_year: 2041) %>
  </div>
  
    <div class="field">
    <%= form.label :lyricist %>
    <%= form.text_field :lyricist %>
  </div>

  <div class="field">
    <%= form.label :composer %>
    <%= form.text_field :composer %>
  </div>
  
<%
=begin
%>
  <div class="field">
    <%= form.label :recorded_albums %>
    <%= form.collection_check_boxes(:album_ids, Album.all, :id, :title)  %>
  </div>
<%
=end
%>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<%= render "home/music-menu" %>

<div class="main">
<h1>L'Arc~en~Ciel 楽曲一覧</h1>
<p>※リリース日順</p>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>|Release</th>
      <th>|Words</th>
      <th>|Music</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <% if user_signed_in? %>
          <td class="song-data"><%= song.id %></td>
          <td class="song-data"><%= song.title %></td>
          <td class="song-data"><%= song.release %></td>
          <td class="song-data"><%= song.lyricist %></td>
          <td class="song-data"><%= song.composer %></td>
          <td class="song-data"><%= link_to 'Show', song %></td>
          <td class="song-data"><%= link_to 'Edit', edit_song_path(song) %></td>
          <td class="song-data"><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else %>
          <td class="song-data"><%= song.title %></td>
          <td class="song-data"><%= song.release %></td>
          <td class="song-data"><%= song.lyricist %></td>
          <td class="song-data"><%= song.composer %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? %>
  <%= link_to 'New Song', new_song_path %>
<% else %>
  <%= paginate @songs %>
<% end %>



</div>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @song.title %>
</p>

<p>
  <strong>Release:</strong>
  <%= @song.release %>
</p>

<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>