config/routes.rb
Rails.application.routes.draw do
  resources :concerts
  devise_for :users
  resources :songs
  resources :albums
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: "home#top"
  get "/about", to: "home#about"
  get "/music", to: "home#music"
  get "/music/albums", to: "albums#albums_index"
  get "/music/albums/:id", to: "albums#show"
  get "/music/singles", to: "albums#singles_index"
  
  get "/music/songs", to: "songs#index"
  
  get "/admin", to: "admin#admin_login"
  
  get "/concerts/:title/detail", to: "concerts#show"
  get "/concerts/:title/destroy", to: "concerts#destroy"
  
  get "/links", to: "home#links"
end

app/models/concert.rb
class Concert < ApplicationRecord
    has_many :setlists
    has_many :songs, through: :setlists
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  PER = 12
  before_action :set_concert, only: [:edit, :update]
  before_action :set_concert_title, only: [:show, :destroy]
  before_action :user_signed_in? , only: [:new, :create, :edit, :update, :destroy]


  # GET /concerts
  def index
    @concert_all = Concert.all
    @concert_index = Concert.pluck(:title).uniq
  end

  # GET /concerts/1
  def show
    @concert_all = Concert.all
    @concert_title = @concert.pluck(:title).uniq
  end

  # GET /concerts/new
  def new
    @concert = Concert.new
    @setlist_songs = []
  end

  # GET /concerts/1/edit
  def edit
    @concert_dates = @concert.setlists.order(date: :asc).pluck(:date).uniq
    @setlist_songs = @concert.songs.order(date: :asc , number: :asc)
  end

  # POST /concerts
  def create
    @concert = Concert.new(concert_params)
    params[:setlist1].each_with_index { | song_id, index | 
      Setlist.create(song_id: song_id, concert_id: @concert.id, date: params[:date1], number: index+1)
    }
    
    params[:setlist2].each_with_index { | song_id, index | 
      Setlist.create(song_id: song_id, concert_id: @concert.id, date: params[:date2], number: index+1)
    }

    params[:setlist3].each_with_index { | song_id, index | 
      Setlist.create(song_id: song_id, concert_id: @concert.id, date: params[:date3], number: index+1)
    }

    params[:setlist4].each_with_index { | song_id, index | 
      Setlist.create(song_id: song_id, concert_id: @concert.id, date: params[:date4], number: index+1)
    }

    params[:setlist5].each_with_index { | song_id, index | 
      Setlist.create(song_id: song_id, concert_id: @concert.id, date: params[:date5], number: index+1)
    }

    params[:setlist6].each_with_index { | song_id, index | 
      Setlist.create(song_id: song_id, concert_id: @concert.id, date: params[:date6], number: index+1)
    }

    params[:setlist7].each_with_index { | song_id, index | 
      Setlist.create(song_id: song_id, concert_id: @concert.id, date: params[:date7], number: index+1)
    }


    if @concert.save
      redirect_to @concert, notice: 'Concert was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /concerts/1
  def update
    @concert.setlists.destroy_all
    params[:setlist1].each_with_index { | song_id, index | 
      Setlist.create(song_id: song_id, concert_id: @concert.id, date: params[:date1], number: index+1)
    }

    params[:setlist2].each_with_index { | song_id, index | 
      Setlist.create(song_id: song_id, concert_id: @concert.id, date: params[:date2], number: index+1)
    }

    params[:setlist3].each_with_index { | song_id, index | 
      Setlist.create(song_id: song_id, concert_id: @concert.id, date: params[:date3], number: index+1)
    }

    params[:setlist4].each_with_index { | song_id, index | 
      Setlist.create(song_id: song_id, concert_id: @concert.id, date: params[:date4], number: index+1)
    }

    params[:setlist5].each_with_index { | song_id, index | 
      Setlist.create(song_id: song_id, concert_id: @concert.id, date: params[:date5], number: index+1)
    }

    params[:setlist6].each_with_index { | song_id, index | 
      Setlist.create(song_id: song_id, concert_id: @concert.id, date: params[:date6], number: index+1)
    }

    params[:setlist7].each_with_index { | song_id, index | 
      Setlist.create(song_id: song_id, concert_id: @concert.id, date: params[:date7], number: index+1)
    }
    
    if @concert.update(concert_params)
      redirect_to @concert, notice: 'Concert was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /concerts/1
  def destroy
    @concert.each do |concert|
      concert.destroy
    end
    redirect_to concerts_url, notice: 'Concert was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concert
      @concert = Concert.find(params[:id])
    end
    
    def set_concert_title
      @concert = Concert.where(title: params[:title])
    end

    # Only allow a trusted parameter "white list" through.
    def concert_params
      params.require(:concert).permit(:title , :place)
    end
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/views/concerts/_edit-form.html.erb
<%= form_with(model: concert, local: true) do |form| %>
  <% if concert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(concert.errors.count, "error") %> prohibited this concert from being saved:</h2>

      <ul>
      <% concert.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  
  <div class="field">
    <%= form.label :place %>
    <%= form.text_field :place %>
  </div>
  
  <% day_setlists =  concert.setlists.where(date: @concert_dates[0]) %>
  <div class="field">
    <strong>date1</strong>
    <%= date_field_tag 'date1', day_setlists[0].nil? ? "" : day_setlists[0].date, class: "form-control"%>
  </div>
  <strong>Setlist</strong>
  <% (1..30).each do |n| %>
    <div class="field">
      <%= text_field_tag 'setlist1[]', day_setlists[n-1].nil? ? "" : day_setlists[n-1].song_id, class: "form-control", placeholder: "No.#{n}" %>
    </div>
  <% end %>
  

  <% day_setlists =  concert.setlists.where(date: @concert_dates[1]) %>
  <div class="field">
    <strong>date2</strong>
    <%= date_field_tag 'date2', day_setlists[0].nil? ? "" : day_setlists[0].date, class: "form-control"%>
  </div>
  <strong>Setlist</strong>
  <% (1..30).each do |n| %>
    <div class="field">
      <%= text_field_tag 'setlist2[]', day_setlists[n-1].nil? ? "" : day_setlists[n-1].song_id, class: "form-control", placeholder: "No.#{n}" %>
    </div>
  <% end %>
  

  <% day_setlists =  concert.setlists.where(date: @concert_dates[2]) %>
  <div class="field">
    <strong>date3</strong>
    <%= date_field_tag 'date3', day_setlists[0].nil? ? "" : day_setlists[0].date, class: "form-control"%>
  </div>
  <strong>Setlist</strong>
  <% (1..30).each do |n| %>
    <div class="field">
      <%= text_field_tag 'setlist3[]', day_setlists[n-1].nil? ? "" : day_setlists[n-1].song_id, class: "form-control", placeholder: "No.#{n}" %>
    </div>
  <% end %>

  
  <% day_setlists =  concert.setlists.where(date: @concert_dates[3]) %>
  <div class="field">
    <strong>date4</strong>
    <%= date_field_tag 'date4', day_setlists[0].nil? ? "" : day_setlists[0].date, class: "form-control"%>
  </div>
  <strong>Setlist</strong>
  <% (1..30).each do |n| %>
    <div class="field">
      <%= text_field_tag 'setlist4[]', day_setlists[n-1].nil? ? "" : day_setlists[n-1].song_id, class: "form-control", placeholder: "No.#{n}" %>
    </div>
  <% end %>

  
  <% day_setlists =  concert.setlists.where(date: @concert_dates[4]) %>
  <div class="field">
    <strong>date5</strong>
    <%= date_field_tag 'date5', day_setlists[0].nil? ? "" : day_setlists[0].date, class: "form-control"%>
  </div>
  <strong>Setlist</strong>
  <% (1..30).each do |n| %>
    <div class="field">
      <%= text_field_tag 'setlist5[]', day_setlists[n-1].nil? ? "" : day_setlists[n-1].song_id, class: "form-control", placeholder: "No.#{n}" %>
    </div>
  <% end %>

  
  <% day_setlists =  concert.setlists.where(date: @concert_dates[5]) %>
  <div class="field">
    <strong>date6</strong>
    <%= date_field_tag 'date6', day_setlists[0].nil? ? "" : day_setlists[0].date, class: "form-control"%>
  </div>
  <strong>Setlist</strong>
  <% (1..30).each do |n| %>
    <div class="field">
      <%= text_field_tag 'setlist6[]', day_setlists[n-1].nil? ? "" : day_setlists[n-1].song_id, class: "form-control", placeholder: "No.#{n}" %>
    </div>
  <% end %>

  
  <% day_setlists =  concert.setlists.where(date: @concert_dates[6]) %>
  <div class="field">
    <strong>date7</strong>
    <%= date_field_tag 'date7', day_setlists[0].nil? ? "" : day_setlists[0].date, class: "form-control"%>
  </div>
  <strong>Setlist</strong>
  <% (1..30).each do |n| %>
    <div class="field">
      <%= text_field_tag 'setlist7[]', day_setlists[n-1].nil? ? "" : day_setlists[n-1].song_id, class: "form-control", placeholder: "No.#{n}" %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
  <% end %>

app/views/concerts/_show-concert.html.erb
<% dates = Setlist.where(concert_id: concert.id).pluck(:date).uniq %>
<!-- concert.songs.order(date: :asc).(:date).uniq -->

<div class="container">
<div class="row">
<% dates.each do |date| %>
<div class="col-6">
  <h5>
    <%= date %>
    <%= concert.place %>
  </h5>
  <br>
  <h6>Setlist</h6>
  <% concert.setlists.where(date: date).order(number: :asc).each do |song| %>
    <h5>
      <%= "#{song.number}." %>
      <%= Song.find(song.song_id).title %>
    </h5>
  <% end %>
</div>
<% end %>
</div>
</div>

app/views/concerts/edit.html.erb
<h1>Editing Concert</h1>

<%= render 'edit-form', concert: @concert %>

<%= link_to 'Show', @concert %> |
<%= link_to 'Back', concerts_path %>

app/views/concerts/index.html.erb
<%= render "home/concert-menu" %>

<div class="main">
  
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @concert_index.each do |concert| %>
      <tr>
        <td class="concert-link"><%= link_to concert , "/concerts/#{concert}/detail" %></td>
        <% if user_signed_in? %>
          <td><%= link_to 'Show', "/concerts/#{concert}/detail" %></td>
          <td><%= link_to 'Destroy', "/concerts/#{concert}/destroy" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? %>
  <%= link_to 'New Concert', new_concert_path %>
<% end %>

</div>

app/views/concerts/new.html.erb
<h1>New Concert</h1>

<%= render 'form', concert: @concert %>

<%= link_to 'Back', concerts_path %>

app/views/concerts/show.html.erb
<div class="main">

<p id="notice"><%= notice %></p>

<div class="contents">
  <div cLass="title">
    <h2><%= "#{@concert_title[0]}" %></h2>
  </div>

  <% @concert.each do |concert| %>
    <%= render 'show-concert', songs: concert.songs.order(date: :asc , number: :asc), concert: concert %>
    <% if user_signed_in? %>
      <%= link_to 'Edit', edit_concert_path(concert) %>
    <% end %>
  <% end %>
</div>
<%= link_to 'Back', concerts_path %>


</div>