config/routes.rb
Rails.application.routes.draw do
  resources :concerts
  devise_for :users
  resources :songs
  resources :albums
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: "home#top"
  get "/about", to: "home#about"
  get "/music", to: "home#music"
  get "/music/albums", to: "albums#albums_index"
  get "/music/albums/:id", to: "albums#show"
  get "/music/singles", to: "albums#singles_index"
  
  get "/music/songs", to: "songs#index"
  
  get "/admin", to: "admin#admin_login"
  
  get "/concerts/:title/detail", to: "concerts#show"
  get "/concerts/:title/destroy", to: "concerts#destroy"
  
  get "/links", to: "home#links"
end

app/models/album.rb
class Album < ApplicationRecord
    has_many :album_songs
    has_many :songs, through: :album_songs
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  PER = 12
  before_action :set_album, only: [:show, :edit, :update, :destroy]
  before_action :user_signed_in? , only: [:new, :create, :edit, :update, :destroy]

  # GET /albums
  # GET /albums.json
  def index
    #@albums = Album.page(params[:page]).per(PER)
  end

  def albums_index
    @albums = Album.where(single: false).page(params[:page]).per(PER)
    @is_album = true
    render action: :index
  end
  
  def singles_index
    @albums = Album.where(single: true).page(params[:page]).per(PER)
    @is_album = false
    render action: :index
  end
  
  # GET /albums/1
  # GET /albums/1.json
  def show
    
  end

  # GET /albums/new
  def new
    @album = Album.new
    @recorded_songs = []
  end

  # GET /albums/1/edit
  def edit
    @recorded_songs = @album.songs.order(number: :asc)
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)
    params[:recorded_songs].each_with_index { | song_id, index | 
      AlbumSong.create(song_id: song_id, album_id: @album.id, number: index+1)
    }
    
    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    edit_album = Album.find(params[:id])
    edit_album.album_songs.destroy_all
    params[:recorded_songs].each_with_index { | song_id, index | 
      AlbumSong.create(song_id: song_id, album_id: edit_album.id, number: index+1)
    }
    
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to "/music", notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:title, :release, :single)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<%= form_with(model: album, local: true) do |form| %>
  <% if album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :release %>
    <%= form.date_select( :release , start_year: 1991 , end_year: 2041) %>
  </div>

  <div class="field">
    <%= form.label :single %>
    <%= form.check_box :single %>
  </div>

  <div class="field">
    <%= text_field_tag 'recorded_songs[]', @recorded_songs[0].nil? ? '': @recorded_songs[0].id, class: "form-control" %>
  </div>
  
  <div class="field">
    <%= text_field_tag 'recorded_songs[]', @recorded_songs[1].nil? ? '': @recorded_songs[1].id, class: "form-control" %>
  </div>
  

  <div class="field">
    <%= text_field_tag 'recorded_songs[]', @recorded_songs[2].nil? ? '': @recorded_songs[2].id, class: "form-control" %>
  </div>
  

  <div class="field">
    <%= text_field_tag 'recorded_songs[]', @recorded_songs[3].nil? ? '': @recorded_songs[3].id, class: "form-control" %>
  </div>
  

  <div class="field">
    <%= text_field_tag 'recorded_songs[]', @recorded_songs[4].nil? ? '': @recorded_songs[4].id, class: "form-control" %>
  </div>
  

  <div class="field">
    <%= text_field_tag 'recorded_songs[]', @recorded_songs[5].nil? ? '': @recorded_songs[5].id, class: "form-control" %>
  </div>
  

  <div class="field">
    <%= text_field_tag 'recorded_songs[]', @recorded_songs[6].nil? ? '': @recorded_songs[6].id, class: "form-control" %>
  </div>
  

  <div class="field">
    <%= text_field_tag 'recorded_songs[]', @recorded_songs[7].nil? ? '': @recorded_songs[7].id, class: "form-control" %>
  </div>
  

  <div class="field">
    <%= text_field_tag 'recorded_songs[]', @recorded_songs[8].nil? ? '': @recorded_songs[8].id, class: "form-control" %>
  </div>
  

  <div class="field">
    <%= text_field_tag 'recorded_songs[]', @recorded_songs[9].nil? ? '': @recorded_songs[9].id, class: "form-control" %>
  </div>
  

  <div class="field">
    <%= text_field_tag 'recorded_songs[]', @recorded_songs[10].nil? ? '': @recorded_songs[10].id, class: "form-control" %>
  </div>
  

  <div class="field">
    <%= text_field_tag 'recorded_songs[]', @recorded_songs[11].nil? ? '': @recorded_songs[11].id, class: "form-control" %>
  </div>
  

  <div class="field">
    <%= text_field_tag 'recorded_songs[]', @recorded_songs[12].nil? ? '': @recorded_songs[12].id, class: "form-control" %>
  </div>
  

  <div class="field">
    <%= text_field_tag 'recorded_songs[]', @recorded_songs[13].nil? ? '': @recorded_songs[13].id, class: "form-control" %>
  </div>
  

  <div class="field">
    <%= text_field_tag 'recorded_songs[]', @recorded_songs[14].nil? ? '': @recorded_songs[14].id, class: "form-control" %>
  </div>
  

  <div class="field">
    <%= text_field_tag 'recorded_songs[]', @recorded_songs[15].nil? ? '': @recorded_songs[15].id, class: "form-control" %>
  </div>
  

  <div class="field">
    <%= text_field_tag 'recorded_songs[]', @recorded_songs[16].nil? ? '': @recorded_songs[16].id, class: "form-control" %>
  </div>
  

  <div class="field">
    <%= text_field_tag 'recorded_songs[]', @recorded_songs[17].nil? ? '': @recorded_songs[17].id, class: "form-control" %>
  </div>
  

  <div class="field">
    <%= text_field_tag 'recorded_songs[]', @recorded_songs[18].nil? ? '': @recorded_songs[18].id, class: "form-control" %>
  </div>
  

  <div class="field">
    <%= text_field_tag 'recorded_songs[]', @recorded_songs[19].nil? ? '': @recorded_songs[19].id, class: "form-control" %>
  </div>
  

  <div class="field">
    <%= text_field_tag 'recorded_songs[]', @recorded_songs[20].nil? ? '': @recorded_songs[20].id, class: "form-control" %>
  </div>
  

  <div class="field">
    <%= text_field_tag 'recorded_songs[]', @recorded_songs[21].nil? ? '': @recorded_songs[21].id, class: "form-control" %>
  </div>
  

  <div class="field">
    <%= text_field_tag 'recorded_songs[]', @recorded_songs[22].nil? ? '': @recorded_songs[22].id, class: "form-control" %>
  </div>
  

  <div class="field">
    <%= text_field_tag 'recorded_songs[]', @recorded_songs[23].nil? ? '': @recorded_songs[23].id, class: "form-control" %>
  </div>
  

  <div class="field">
    <%= text_field_tag 'recorded_songs[]', @recorded_songs[24].nil? ? '': @recorded_songs[24].id, class: "form-control" %>
  </div>
  

  <div class="field">
    <%= text_field_tag 'recorded_songs[]', @recorded_songs[25].nil? ? '': @recorded_songs[25].id, class: "form-control" %>
  </div>
  

  <div class="field">
    <%= text_field_tag 'recorded_songs[]', @recorded_songs[26].nil? ? '': @recorded_songs[26].id, class: "form-control" %>
  </div>
  

  <div class="field">
    <%= text_field_tag 'recorded_songs[]', @recorded_songs[27].nil? ? '': @recorded_songs[27].id, class: "form-control" %>
  </div>
  

  <div class="field">
    <%= text_field_tag 'recorded_songs[]', @recorded_songs[28].nil? ? '': @recorded_songs[28].id, class: "form-control" %>
  </div>
  

  <div class="field">
    <%= text_field_tag 'recorded_songs[]', @recorded_songs[29].nil? ? '': @recorded_songs[29].id, class: "form-control" %>
  </div>
  

  <div class="field">
    <%= text_field_tag 'recorded_songs[]', @recorded_songs[30].nil? ? '': @recorded_songs[30].id, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/albums/_show-album.html.erb
<table>
    <thead>
    </thead>
    <tbody>
        <tr>
            <td>
                <p><%= "#{@order}." %></p>
            </td>
            <td>
                <h4><%= song.title %></h4>
            </td>
        </tr>
    </tbody>
</table>

<% @order += 1 %> 

app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', 
  if @album.single == false
    "/music/albums"
  else
    "/music/singles"
  end
%>

app/views/albums/index.html.erb
<%= render "home/music-menu" %>

<div class="main index">
  <% if @is_album == true %>
    <h1>L'Arc~en~Ciel Albums</h1>
  <% else %>
    <h1>L'Arc~en~Ciel Singles</h1>
  <% end %>
  
  <div class="container">
    <div class="row">
      <% @albums.each do |album| %>
        <div class="col-3 album-box">
          <%= link_to "/music/albums/#{album.id}" , class: "album-detail" do %>
            <div><%= album.title %></div>
            <div><%= album.release %></div>
            <% if user_signed_in? %>
              <div><%= link_to 'Edit', edit_album_path(album) %></div>
              <div><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          <% end %>
        </div>
        <% end %>
    </div>
    
    <br>
    <%= paginate @albums %> 
  </div>

</div><!-- mainクラス -->

  <% if user_signed_in? %>
    <%= link_to 'New Album', new_album_path %>
  <% end %>
    

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Back_to_album_index', "/music/albums" %>
<%= link_to 'Back_to_single_index', "/music/singles" %>

app/views/albums/show.html.erb
<%= render "home/music-menu" %>

<div class="main">

<h3 id="album-title">
  <strong>Title:</strong>
  <%= @album.title %>
</h3>

<h4 id="release-date">
  <strong>Release:</strong>
  <%= @album.release %>
</h4>

<h4 id="songs-header" style="font-size: 25px;">収録曲</h4>

<!-- Song No. -->
<% @order = 1 %>
<% @album.songs.order(number: :asc).each do |song| %>
  <%= render 'show-album', song: song %>
<% end %>


<% if user_signed_in? %>

<p>
  <strong>Single:</strong>
  <%= @album.single %>
</p>

<%= link_to 'Edit', edit_album_path(@album) %> |
<% end %>
<%= link_to 'Back', @album.single == false ? "/music/albums" : "/music/singles" %>

 

</div>